//! On-chain slash verification (ADR-008).
//!
//! Given a *submitted* identity secret plus K moderation certificates (each
//! carrying a moderator-signed Shamir share), this verifies — without
//! running Lagrange — that the secret genuinely produced every share, that
//! every cert has ≥ N valid moderator signatures, and that the resulting
//! commitment is an un-revoked member of the tree.
//!
//! The guest calls [`verify_slash`]; host tests call it too. Sig-checking
//! logic is re-implemented here (not imported from `moderation-cert`)
//! because that crate depends on this one — the reverse dep would cycle.
//! The signing-message format MUST stay byte-identical to
//! `moderation_cert::message_to_sign`.

use alloc::vec::Vec;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use sha2::{Digest, Sha256};

use crate::shamir::{self, Fr};
use crate::{
    Commitment, ForumConfig, Hash, MerklePath, ModerationCertificateWire, ModeratorPubKey,
    TREE_DEPTH,
};

/// Must match `moderation_cert::DOMAIN`.
pub const MODCERT_DOMAIN: &[u8] = b"forum-protocol/v1/modcert";

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SlashVerifyError {
    BelowKThreshold { k: u8, got: usize },
    DuplicateContent,
    CertBelowNThreshold { idx: usize },
    UnknownSigner { idx: usize },
    DuplicateSigner { idx: usize },
    BadSignature { idx: usize },
    BadPubkey { idx: usize },
    /// share_x in the cert isn't H(secret, content_id) — the share wasn't
    /// generated by this secret for this content.
    ShareXMismatch { idx: usize },
    /// share_y isn't poly(share_x) for the secret's polynomial.
    ShareYMismatch { idx: usize },
    NotInTree,
    AlreadyRevoked,
}

fn sha256_concat(parts: &[&[u8]]) -> [u8; 32] {
    let mut h = Sha256::new();
    for p in parts {
        h.update(p);
    }
    let mut out = [0u8; 32];
    out.copy_from_slice(&h.finalize()[..]);
    out
}

pub fn commitment_of(secret: &[u8; 32]) -> Commitment {
    sha256_concat(&[crate::tags::COMMIT, secret])
}

fn node_hash(left: &Hash, right: &Hash) -> Hash {
    sha256_concat(&[crate::tags::NODE, left, right])
}

fn fold_path(leaf: &Hash, path: &MerklePath, index: u32) -> Hash {
    let mut cur = *leaf;
    for level in 0..TREE_DEPTH {
        let sibling = &path[level];
        let bit = (index >> level) & 1;
        cur = if bit == 0 {
            node_hash(&cur, sibling)
        } else {
            node_hash(sibling, &cur)
        };
    }
    cur
}

/// Byte-identical to `moderation_cert::message_to_sign`.
fn modcert_message(content_id: &Hash, strike_index: u8, share_x: &Hash, share_y: &Hash) -> [u8; 32] {
    sha256_concat(&[
        MODCERT_DOMAIN,
        content_id,
        &[strike_index],
        share_x,
        share_y,
    ])
}

/// Verify a slash. Returns the slashed commitment on success.
///
/// `secret` is the slasher's claimed reconstruction. We never trust it
/// blindly: the share-binding checks (b, c below) make a forged secret
/// fail unless the slasher actually holds K genuine shares of it.
pub fn verify_slash(
    secret: &[u8; 32],
    certs: &[ModerationCertificateWire],
    config: &ForumConfig,
    tree_root: Hash,
    leaf_index: u32,
    merkle_path: &MerklePath,
    revocation_set: &[Commitment],
) -> Result<Commitment, SlashVerifyError> {
    // 1. Enough certificates.
    if certs.len() < config.k_threshold as usize {
        return Err(SlashVerifyError::BelowKThreshold {
            k: config.k_threshold,
            got: certs.len(),
        });
    }

    // 2. Distinct content_ids (else duplicate share-x degrades Lagrange and
    //    lets a slasher pad with copies).
    for i in 0..certs.len() {
        for j in 0..i {
            if certs[i].content_id == certs[j].content_id {
                return Err(SlashVerifyError::DuplicateContent);
            }
        }
    }

    // 3. Polynomial implied by the submitted secret.
    let coeffs = shamir::polynomial_coefficients(secret, config.k_threshold as usize);

    for (idx, cert) in certs.iter().enumerate() {
        // a. ≥ N valid signatures from distinct configured moderators.
        let msg = modcert_message(
            &cert.content_id,
            cert.strike_index,
            &cert.share_x,
            &cert.share_y,
        );
        let mut valid_signers: Vec<ModeratorPubKey> = Vec::new();
        for (pub_bytes, sig) in &cert.signatures {
            if !config.moderators.contains(pub_bytes) {
                return Err(SlashVerifyError::UnknownSigner { idx });
            }
            if valid_signers.contains(pub_bytes) {
                return Err(SlashVerifyError::DuplicateSigner { idx });
            }
            let vk = VerifyingKey::from_bytes(pub_bytes)
                .map_err(|_| SlashVerifyError::BadPubkey { idx })?;
            let signature = Signature::from_bytes(&sig.0);
            vk.verify(&msg, &signature)
                .map_err(|_| SlashVerifyError::BadSignature { idx })?;
            valid_signers.push(*pub_bytes);
        }
        if valid_signers.len() < config.n_threshold as usize {
            return Err(SlashVerifyError::CertBelowNThreshold { idx });
        }

        // b. share_x must be H(secret, content_id) — binds the share to this
        //    secret and this content. A forged secret can't reproduce it.
        let expected_x = shamir::derive_share_x(secret, &cert.content_id);
        if shamir::fr_from_bytes(&cert.share_x) != expected_x {
            return Err(SlashVerifyError::ShareXMismatch { idx });
        }

        // c. share_y must lie on the secret's polynomial at share_x.
        let x = shamir::fr_from_bytes(&cert.share_x);
        let expected_y: Fr = shamir::poly_eval(&coeffs, x);
        if shamir::fr_from_bytes(&cert.share_y) != expected_y {
            return Err(SlashVerifyError::ShareYMismatch { idx });
        }
    }

    // 4. commitment must be a leaf in the tree.
    let commitment = commitment_of(secret);
    if revocation_set.iter().any(|r| r == &commitment) {
        return Err(SlashVerifyError::AlreadyRevoked);
    }
    if fold_path(&commitment, merkle_path, leaf_index) != tree_root {
        return Err(SlashVerifyError::NotInTree);
    }

    Ok(commitment)
}
